# Generated by Django 2.2.3 on 2019-12-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.CharField(choices=[('medicine', 'Medicine'), ('parlour', 'Parlour'), ('accessories', 'Accessories'), ('healthcare', 'HealthCare')], default='healthcare', max_length=15)),
            ],
        ),
    ]
