# Generated by Django 2.2.3 on 2020-01-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191220_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('timeslot', models.DateTimeField()),
            ],
        ),
    ]
